"""Added language to posts

Revision ID: 269c1c19ad17
Revises: dd2366c7b84f
Create Date: 2021-10-23 08:13:09.200944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269c1c19ad17'
down_revision = 'dd2366c7b84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
